import Foundation
@testable import Splats
import Testing

/// Load/decode timing for the CPU reader paths (`SplatReader`: PLY, SOG-CPU,
/// SPZ v2/v3/v4). Reports median/min ms and MB/s per file. Timing-sensitive, so
/// it's skipped on CI and prints results rather than asserting on durations —
/// the only hard check is that each file decodes a non-empty cloud.
@Suite(.disabled(if: ProcessInfo.processInfo.environment["CI"] != nil, "Timing benchmark; unreliable on CI"))
struct SplatLoadBenchmarkTests {
    private let warmup = 1
    private let iterations = 5

    @Test
    func benchmarkSplatLoading() throws {
        func pad(_ s: String, _ width: Int) -> String {
            s.count >= width ? s : String(repeating: " ", count: width - s.count) + s
        }

        var rows: [String] = []
        rows.append(pad("file", 22) + pad("splats", 11) + pad("MB", 9) + pad("med ms", 10) + pad("min ms", 9) + pad("MB/s", 9))

        for url in benchmarkFiles() {
            let size = ((try? FileManager.default.attributesOfItem(atPath: url.path))?[.size] as? Int) ?? 0
            let mb = Double(size) / 1_000_000

            var count = 0
            func f(_ v: Double, _ d: Int) -> String { String(format: "%.\(d)f", v) }
            do {
                let times = try measure(warmup: warmup, iterations: iterations) {
                    let reader = try SplatReader(url: url)
                    var n = 0
                    try reader.read { _, _ in n += 1 }
                    count = n
                }
                #expect(count > 0, "\(url.lastPathComponent) decoded no splats")
                let med = median(times)
                let mn = times.min() ?? 0
                let mbps = med > 0 ? mb / med : 0
                rows.append(pad(url.lastPathComponent, 22) + pad("\(count)", 11) + pad(f(mb, 2), 9)
                    + pad(f(med * 1_000, 2), 10) + pad(f(mn * 1_000, 2), 9) + pad(f(mbps, 0), 9))
            } catch {
                rows.append(pad(url.lastPathComponent, 22) + "  FAILED: \(error)")
                Issue.record("\(url.lastPathComponent) failed to load: \(error)")
            }
        }

        let table = "Splat load benchmark — median of \(iterations) (\(warmup) warmup)\n" + rows.joined(separator: "\n")
        print(table)
        // Test-runner stdout is often swallowed; also drop the table on disk.
        try? table.write(to: FileManager.default.temporaryDirectory.appendingPathComponent("splat-load-benchmark.txt"), atomically: true, encoding: .utf8)
    }

    /// Bundled fixtures plus the larger `Samples/` clouds when present. Missing
    /// files are skipped so the benchmark runs in any checkout.
    private func benchmarkFiles() -> [URL] {
        var urls: [URL] = []
        for (name, ext) in [("test-grid", "ply"), ("test-grid", "sog"), ("test-grid", "spz"), ("test-grid.v4", "spz")] {
            if let url = Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "Fixtures") {
                urls.append(url)
            }
        }
        // Large synthetic clouds generated by `just bench` into Fixtures/Bench/
        // (gitignored). Resolved from source so they don't need to be bundled.
        let bench = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/Bench")
        for name in ["bench-grid.ply", "bench-grid.sog", "bench-grid.v3.spz", "bench-grid.v4.spz"] {
            let url = bench.appendingPathComponent(name)
            if FileManager.default.fileExists(atPath: url.path) {
                urls.append(url)
            }
        }
        return urls
    }

    private func measure(warmup: Int, iterations: Int, _ body: () throws -> Void) rethrows -> [TimeInterval] {
        for _ in 0..<warmup {
            try body()
        }
        var times: [TimeInterval] = []
        for _ in 0..<iterations {
            let start = ContinuousClock.now
            try body()
            let elapsed = ContinuousClock.now - start
            times.append(Double(elapsed.components.seconds) + Double(elapsed.components.attoseconds) * 1e-18)
        }
        return times
    }

    private func median(_ values: [TimeInterval]) -> TimeInterval {
        let sorted = values.sorted()
        return sorted.isEmpty ? 0 : sorted[sorted.count / 2]
    }
}
