name: Swift
on:
  push:
  pull_request:

env:
  XCODE_VERSION: "26.2"

jobs:
  swiftlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  build-and-test:
    runs-on: "macos-26"
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download MetalToolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Trust plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
      - name: Build (macOS)
        run: swift build -v --disable-sandbox
      - name: Test (macOS)
        run: swift test -v --disable-sandbox
        env:
          CI: "true"

  build-simple-demo:
    runs-on: "macos-26"
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "generic/platform=iOS"
          - "generic/platform=xrOS"
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download MetalToolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Trust plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
      - name: Build Simple Demo (${{ matrix.destination }})
        run: |
          xcodebuild build \
            -project Examples/MetalSprocketsGaussianSplatsDemo/MetalSprocketsGaussianSplatsDemo.xcodeproj \
            -scheme MetalSprocketsGaussianSplatsDemo \
            -destination '${{ matrix.destination }}' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO
